name: "Greet With A Random Joke"
on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    name: setup environment
    runs-on: ubuntu-latest
    steps:
      - name: mast joke mara
        uses: deep5050/MastJokeMara@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issue_msg: |
            Hi, {{author}},
            Thanks for opening an issue :blue_heart: your issue will be seen by maintainers soon.\n
            Contributors :people_holding_hands:  like you make the open source community :earth_africa:  such an amazing place to learn :book: ,
             inspire :angel:, and create :art: .\nWe will investigate :eyes:  and get back to you as soon as possible :+1: . 
             Just make sure you have given us sufficient information :information_source:.\n\nBy that time enjoy this joke :point_down: , 
             hope you like it :smile:
            
            {{joke}}
                      
          PR_msg: |
            Hi, {{author}},
            Thanks for opening an PR :blue_heart: your PR will be mergerd soon if it donot have any conflist make sure to watch contributing.md file .\n
            Contributors :people_holding_hands:  like you make the open source community :earth_africa:  such an amazing place to learn :book: ,
             inspire :angel:, and create :art: .\nWe will investigate :eyes:  and get back to you as soon as possible :+1: . 
             Just make sure you have given us sufficient information :information_source:.\n\nBy that time enjoy this joke :point_down: , 
             hope you like it :smile:

            {{joke}}
